language: r
cache: packages
r: release

env:
  global:
  - _R_CHECK_DONTTEST_EXAMPLES_=FALSE
  
install:
- R -e 'install.packages(c("sommer","ggplot2","abind","MASS","gtools","CompQuadForm","Matrix","RLRsim","mvtnorm","nlme","quadprog","parallel","stats","methods","mappoly","rmarkdown","devtools","knitr"))'

r_build_args: --no-build-vignettes
r_check_args: "--no-vignettes --as-cran --install-args=--build"

r_packages:
- sommer
- ggplot2
- abind
- MASS
- gtools
- CompQuadForm
- Matrix
- RLRsim
- mvtnorm
- nlme
- quadprog
- parallel
- stats
- methods
- mappoly
- rmarkdown
- devtools
- knitr