language: r
cache: packages

#r_packages:
#- devtools

install:
- R -e 'install.packages("devtools")'
- R -e 'install.packages(c("sommer", "ggplot2", "abind", "gtools", "mappoly", "rmarkdown"))'
- R -e 'remotes::install_github("cran/SPA3G")'
- R -e 'remotes::install_github("cran/varComp")'

r_build_args: --no-build-vignettes
r_check_args: --no-vignettes
